spring.application.name=sales-service

server.port=8083

# H2 database
spring.datasource.url=jdbc:h2:mem:salesdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JWT configuration
# security.jwt.secret=${JWT_SECRET} -> USO STANDARD VARIABLES DE ENTORNO
security.jwt.secret=4EOHFVGTHZN6yKAKPhJCDqQxqUIKIaa3dJpCLQWeEUs=

# Catalog service integration
catalog.service.base-url=${CATALOG_SERVICE_URL:http://localhost:8082}

# OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.display-request-duration=true

# Date serialization
spring.jackson.datatype.datetime.write-dates-as-timestamps=false

